# -- App Router values --
enabled: true
serviceAnnotations:

servicePort: 80
containerPort: 80
serviceType: LoadBalancer

nginxConfFile: "nginx/app-nginx.conf"

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

enableLivenessProbe: false