global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

# -- Main api defaults -- #
image:
  fullImageName: ""
  registry: ""
  repository: ""
  tag: ""
  digest: ""
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: [ ]
  ## Enable debug mode
  ##
  debug: false

djangoConfig:
  ENV_SWITCHER_FOR_DYNACONF: TOOL_ENV
  DJANGO_SETTINGS_MODULE: service.settings.base
  DJANGO_DATABASES__default__ENGINE: "django.db.backends.postgresql"
  DJANGO_DATABASES__default__HOST: db_host
  DJANGO_DATABASES__default__NAME: db_name
  DJANGO_DATABASES__default__USER: db_user
  DJANGO_DATABASES__default__PASSWORD: db_pass

  DJANGO_BASE_URL: ""
  DJANGO_DEBUG: "true"
  DJANGO_SECRET_KEY: local

  DJANGO_ENVIRONMENT: development

# -- Main app values --
enabled: true
migrations:
  enabled: false
serviceAnnotations:

updateStrategy:
  type: RollingUpdate

replicaCount: 1

serviceType: LoadBalancer
servicePort:
containerPort:

confFile:
persistence:

mountSecretFile:
  confFile:
    sourcePath: ""
    destinationPath: ""
    content: |-

volumeMounts:

enableLivenessProbe: false
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

migration: [ "migrate" ]

podSecurityContext:
  enabled: false
  fsGroup: 1001
