apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
spec:
  selector:
    matchLabels:
      service: {{ include "common.names.fullname" . }}-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        checksum/router: {{ include (print $.Template.BasePath "/router-cm.yaml") . | sha256sum }}
      labels:
        service: {{ include "common.names.fullname" . }}-deployment
    spec:
      containers:
        - image: nginx
          ports:
            - containerPort: {{ .Values.containerPort }}
          name: {{ include "common.names.fullname" . }}-container
          resources: { }
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: {{ include "common.names.fullname" . }}
      restartPolicy: Always
      volumes:
        - name: {{ include "common.names.fullname" . }}
          configMap:
            name: {{ include "common.names.fullname" . }}-nginx-conf-d