{{- if .Values.confFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
data:
  config.json: |-
{{ .Values.mountSecretFile.confFile.content | indent 4}}
{{- end }}