global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

# -- Main api defaults -- #
defaults: &defaults
  image:
    registry: ""
    repository: ""
    tag: 0.0.1
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]
    ## Enable debug mode
    ##
    debug: false

config: &config
  ENV_SWITCHER_FOR_DYNACONF: TOOL_ENV
  DJANGO_SETTINGS_MODULE: service.settings.base
  DJANGO_DATABASES__default__ENGINE: "django.db.backends.postgresql"
  DJANGO_DATABASES__default__HOST: db_host
  DJANGO_DATABASES__default__NAME: db_name
  DJANGO_DATABASES__default__USER: db_user
  DJANGO_DATABASES__default__PASSWORD: db_pass

  DJANGO_BASE_URL: ""
  DJANGO_DEBUG: "true"
  DJANGO_SECRET_KEY: local

  DJANGO_ENVIRONMENT: development

# -- Main app values --
app:
  <<: *defaults
  config:
    <<: *config
  enabled: true
  migrations:
    enabled: true
  serviceAnnotations:

  serviceType: LoadBalancer
  servicePort: 8000
  containerPort: 8000

  volumeMounts:

  enableLivenessProbe: false
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  migration: [ "migrate" ]

# -- App Router values --
app-router:
  enabled: true
  serviceAnnotations:

  servicePort: 80
  containerPort: 80
  serviceType: LoadBalancer

  nginxConfFile: "nginx/app-nginx.conf"

router:
  endpoints:
    site.name.com:
      "/":
        host: "{{ .Release.Name }}-backend"
        port: 80

